fos_user:
    db_driver: orm
    user_class: App\Entity\User
    firewall_name: main
    from_email:
        address: foo
        sender_name: bar
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            from_email:
                address: resetting@alfresco.com
                sender_name: Manager Resetting

