<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.qEgOqW3' shared service.

return $this->privates['.service_locator.qEgOqW3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'preference' => ['privates', '.errored..service_locator.qEgOqW3.App\\Entity\\Preferences', NULL, 'Cannot autowire service ".service_locator.qEgOqW3": it references class "App\\Entity\\Preferences" but no such service exists.'],
], [
    'preference' => 'App\\Entity\\Preferences',
]);
