<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Entreprise extends \App\Entity\Entreprise implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'lieu', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'evaluationElements', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'manager', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'evaluateures', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'experts', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'eAFs', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'etapes'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'lieu', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'evaluationElements', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'manager', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'evaluateures', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'experts', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'eAFs', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'etapes'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Entreprise $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieu(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieu', []);

        return parent::getLieu();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieu(?string $lieu): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieu', [$lieu]);

        return parent::setLieu($lieu);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvaluationElements(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvaluationElements', []);

        return parent::getEvaluationElements();
    }

    /**
     * {@inheritDoc}
     */
    public function getEvaluationElementsNull(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvaluationElementsNull', []);

        return parent::getEvaluationElementsNull();
    }

    /**
     * {@inheritDoc}
     */
    public function getEvaluationElementsNullByUser(\App\Entity\User $user): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvaluationElementsNullByUser', [$user]);

        return parent::getEvaluationElementsNullByUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function addEvaluationElement(\App\Entity\EvaluationElements $evaluationElement): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEvaluationElement', [$evaluationElement]);

        return parent::addEvaluationElement($evaluationElement);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEvaluationElement(\App\Entity\EvaluationElements $evaluationElement): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEvaluationElement', [$evaluationElement]);

        return parent::removeEvaluationElement($evaluationElement);
    }

    /**
     * {@inheritDoc}
     */
    public function getManager(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManager', []);

        return parent::getManager();
    }

    /**
     * {@inheritDoc}
     */
    public function setManager(?\App\Entity\User $manager): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManager', [$manager]);

        return parent::setManager($manager);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvaluateures(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvaluateures', []);

        return parent::getEvaluateures();
    }

    /**
     * {@inheritDoc}
     */
    public function addEvaluateure(\App\Entity\User $evaluateure): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEvaluateure', [$evaluateure]);

        return parent::addEvaluateure($evaluateure);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEvaluateure(\App\Entity\User $evaluateure): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEvaluateure', [$evaluateure]);

        return parent::removeEvaluateure($evaluateure);
    }

    /**
     * {@inheritDoc}
     */
    public function getExperts(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExperts', []);

        return parent::getExperts();
    }

    /**
     * {@inheritDoc}
     */
    public function addExpert(\App\Entity\User $expert): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExpert', [$expert]);

        return parent::addExpert($expert);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExpert(\App\Entity\User $expert): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExpert', [$expert]);

        return parent::removeExpert($expert);
    }

    /**
     * {@inheritDoc}
     */
    public function getEAFs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEAFs', []);

        return parent::getEAFs();
    }

    /**
     * {@inheritDoc}
     */
    public function addEAF(\App\Entity\EAF $eAF): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEAF', [$eAF]);

        return parent::addEAF($eAF);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEAF(\App\Entity\EAF $eAF): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEAF', [$eAF]);

        return parent::removeEAF($eAF);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtapes(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtapes', []);

        return parent::getEtapes();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtapes(array $etapes): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtapes', [$etapes]);

        return parent::setEtapes($etapes);
    }

}
