<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.HSLLyCC' shared service.

return $this->privates['.service_locator.HSLLyCC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'eAFRepository' => ['privates', 'App\\Repository\\EAFRepository', 'getEAFRepositoryService.php', true],
], [
    'eAFRepository' => 'App\\Repository\\EAFRepository',
]);
