<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.LkxEkjn' shared service.

return $this->privates['.service_locator.LkxEkjn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'eAF' => ['privates', '.errored..service_locator.LkxEkjn.App\\Entity\\EAF', NULL, 'Cannot autowire service ".service_locator.LkxEkjn": it references class "App\\Entity\\EAF" but no such service exists.'],
], [
    'eAF' => 'App\\Entity\\EAF',
]);
