<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMIBOxDc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMIBOxDc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMIBOxDc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMIBOxDc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMIBOxDc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MIBOxDc',
    'container.build_id' => '6f563e67',
    'container.build_time' => 1596903499,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMIBOxDc');
